services:
  # PostgreSQL Database
  - type: pserv
    name: ecommerce-db
    env: docker
    plan: free
    dockerfilePath: ./ecom-backend/Dockerfile.db
    envVars:
      - key: POSTGRES_DB
        value: ecommerce
      - key: POSTGRES_USER
        value: ecomuser
      - key: POSTGRES_PASSWORD
        generateValue: true
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

  # Spring Boot Backend
  - type: web
    name: ecommerce-backend
    env: java
    plan: free
    buildCommand: cd ecom-backend && ./mvnw clean package -DskipTests
    startCommand: cd ecom-backend && java -jar target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ecommerce-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ecommerce-db
          property: password
      - key: SERVER_PORT
        value: 5000
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  # React Frontend
  - type: web
    name: ecommerce-frontend
    env: static
    plan: free
    buildCommand: cd ecom-frontend && npm install && npm run build
    staticPublishPath: ./ecom-frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: ecommerce-backend
          type: web
          property: host
