databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecomuser
    plan: free
    region: oregon

services:
  # Spring Boot Backend
  - type: web
    name: ecommerce-backend
    runtime: docker
    plan: free
    region: oregon
    branch: master
    dockerfilePath: ./ecom-backend/Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ecommerce-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ecommerce-db
          property: password
      - key: SERVER_PORT
        value: 10000
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  # React Frontend
  - type: web
    name: ecommerce-frontend
    runtime: static
    plan: free
    region: oregon
    branch: master
    buildCommand: cd ecom-frontend && npm install && npm run build
    staticPublishPath: ./ecom-frontend/dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_URL
        fromService:
          name: ecommerce-backend
          type: web
          property: hostport
